name: jresearch

channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipywidgets>=0.6.0
  - mkl
  - dask
  - scikit-learn
  - numcodecs
  - pytorch
  - xarray
  - zarr
  - jdcal
  - h5py
  - pymatsolver>=0.2.0
  - discretize
  - scikit-image
  - pip
  - pip:
      - geoana
      - torchvision
      - statsmodels
      - spectrum
      - julian
      - utm
      - git+https://github.com/JKutt/simpeg.git